###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
    ####consul注册中心地址
  cloud:
    consul:
      host: 120.24.161.234
      port: 8500
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
